### ISSUE TITLE
Stworzenie i obsługa okna GUI

### ISSUE THREAD

**Issue by PiorunPL** [PiorunPL/WireWorldJava#6]

**Comment by bastyje** [comment]
## TODO
- [x] obsługa braku ingerencji wyświetlanej struktury w planszę
- [x] umieszczenie struktury w danym miejscu po naciśnięciu LPM (tylko!)
- [x] wyświetlanie mapy
- [x] naprawić błąd z prawą częścią planszy
- [x] obsługa Wire
- [ ] ustawianie planszy proporcjonalnie
- [x] obsługa obracania struktur
- [ ] wyszarzenie/przezroczyste komórki przed zatwierdzeniem ustawienia struktury
- [x] zakreskowanie pól, na których nie można stawiać struktur
